const rows = {
  es: ['Cuenta y contraseña', 'Puedes cambiar tu contraseña cuando quieras. No se exige una longitud mínima ni caracteres especiales.', 'Contraseña actual', 'Nueva contraseña', 'Repetir nueva contraseña', 'Guardar contraseña', 'Guardando…', 'Contraseña cambiada. Este dispositivo sigue conectado.', 'La contraseña actual no es correcta.', 'Las contraseñas no coinciden.', 'Introduce una contraseña.', 'No se pudo guardar. Inténtalo de nuevo.', 'Recordar este dispositivo durante 90 días', 'Eres responsable de custodiar tus credenciales y de elegir la contraseña de tu cuenta. Puedes cerrar sesión cuando dejes de usar este dispositivo.'],
  en: ['Account and password', 'You can change your password whenever you choose. No minimum length or special characters are required.', 'Current password', 'New password', 'Repeat new password', 'Save password', 'Saving…', 'Password changed. This device stays signed in.', 'The current password is incorrect.', 'Passwords do not match.', 'Enter a password.', 'Could not save. Please try again.', 'Remember this device for 90 days', 'You are responsible for keeping your credentials private and choosing your account password. Sign out when you stop using this device.'],
  it: ['Account e password', 'Puoi cambiare la password quando vuoi. Non sono richiesti una lunghezza minima o caratteri speciali.', 'Password attuale', 'Nuova password', 'Ripeti la nuova password', 'Salva password', 'Salvataggio…', 'Password modificata. Questo dispositivo resta connesso.', 'La password attuale non è corretta.', 'Le password non coincidono.', 'Inserisci una password.', 'Salvataggio non riuscito. Riprova.', 'Ricorda questo dispositivo per 90 giorni', 'Sei responsabile della custodia delle credenziali e della scelta della password. Esci quando smetti di usare questo dispositivo.'],
  fr: ['Compte et mot de passe', 'Vous pouvez changer votre mot de passe quand vous le souhaitez. Aucune longueur minimale ni caractère spécial ne sont exigés.', 'Mot de passe actuel', 'Nouveau mot de passe', 'Répéter le nouveau mot de passe', 'Enregistrer le mot de passe', 'Enregistrement…', 'Mot de passe modifié. Cet appareil reste connecté.', 'Le mot de passe actuel est incorrect.', 'Les mots de passe ne correspondent pas.', 'Saisissez un mot de passe.', 'Échec de l’enregistrement. Réessayez.', 'Mémoriser cet appareil pendant 90 jours', 'Vous êtes responsable de la confidentialité de vos identifiants et du choix de votre mot de passe. Déconnectez-vous lorsque vous cessez d’utiliser cet appareil.'],
  pt: ['Conta e palavra-passe', 'Pode alterar a palavra-passe quando quiser. Não são exigidos comprimento mínimo nem caracteres especiais.', 'Palavra-passe atual', 'Nova palavra-passe', 'Repetir nova palavra-passe', 'Guardar palavra-passe', 'A guardar…', 'Palavra-passe alterada. Este dispositivo continua ligado.', 'A palavra-passe atual está incorreta.', 'As palavras-passe não coincidem.', 'Introduza uma palavra-passe.', 'Não foi possível guardar. Tente novamente.', 'Lembrar este dispositivo durante 90 dias', 'É responsável por guardar as suas credenciais e escolher a palavra-passe da conta. Termine a sessão quando deixar de utilizar este dispositivo.'],
};
const keys = ['title', 'hint', 'current', 'new', 'confirm', 'save', 'saving', 'success', 'incorrect', 'mismatch', 'required', 'error', 'remember', 'responsibility'];
export const ACCOUNT_TRANSLATIONS = Object.fromEntries(Object.entries(rows).map(([language, values]) => [language, Object.fromEntries(keys.map((key, i) => [`account.${key}`, values[i]]))]));
