const es = {
  setup: "Ficha del ingrediente", active: "Activo en esta tienda", inactive: "Pendiente de activar",
  price: "Precio base de armado", priceHelp: "Referencia para configurar este ingrediente en las pizzas. El precio final al cliente se define en los productos y extras.",
  scope: "Precio, descripción y foto se guardan solo para tu negocio.", suggestion: "Usar sugerido: {price}", suggestionHelp: "Media de otros ingredientes activos de esta categoría en tu negocio.",
  aliases: "Alias del catálogo global", noAliases: "No hay otros nombres publicados. Puedes buscarlo por su nombre principal.",
  aliasesHelp: "Los alias son nombres alternativos para encontrar el mismo ingrediente. Se gestionan y revisan en Global Manager.",
  allergens: "Alérgenos del catálogo global", unknown: "Alérgenos sin informar", allergenHelp: "Una lista vacía no confirma que no tenga alérgenos. La información debe contrastarse con la ficha del proveedor.",
  knownHelp: "Datos del catálogo global. Comprueba que coincidan con el producto de tu proveedor; las correcciones se gestionan en Global Manager.",
  description: "Descripción para tu negocio", placeholder: "Ej. Pechuga cocida, cortada en tiras.",
  identity: "Identidad y traducciones", reviewed: "Revisado", pending: "Pendiente de revisión", missing: "Sin completar", reviewHelp: "Las traducciones automáticas se publican en el backoffice después de revisarlas en Global Manager.",
  photo: "Subir foto", changePhoto: "Cambiar foto", photoHelp: "JPG, PNG o WebP · hasta 5 MB", cancel: "Cancelar", save: "Guardar cambios", activate: "Guardar y activar", saving: "Guardando…", deactivate: "Desactivar", close: "Cerrar",
  invalidPrice: "Introduce un precio mayor que cero, con un máximo de dos decimales.", invalidPhoto: "Usa una foto JPG, PNG o WebP de hasta 5 MB.", saveError: "No se pudo guardar. Tus cambios siguen aquí para reintentar.",
};
const en = {
  setup: "Ingredient details", active: "Active in this store", inactive: "Awaiting activation", price: "Base ingredient price",
  priceHelp: "Reference for configuring this ingredient in pizzas. Final customer prices are set in products and extras.", scope: "Price, description and photo are saved for your business only.",
  suggestion: "Use suggestion: {price}", suggestionHelp: "Average of other active ingredients in this category for your business.",
  aliases: "Global catalog aliases", noAliases: "No alternative names published. You can search by the main name.", aliasesHelp: "Aliases are alternative names for the same ingredient. They are managed and reviewed in Global Manager.",
  allergens: "Global catalog allergens", unknown: "Allergen information missing", allergenHelp: "An empty list does not confirm the absence of allergens. Check the supplier's product information.", knownHelp: "Global catalog data. Check it matches your supplier's product; corrections are managed in Global Manager.",
  description: "Description for your business", placeholder: "E.g. Cooked chicken breast, cut into strips.", identity: "Identity and translations", reviewed: "Reviewed", pending: "Awaiting review", missing: "Not completed", reviewHelp: "Automatic translations appear in the backoffice after review in Global Manager.",
  photo: "Upload photo", changePhoto: "Change photo", photoHelp: "JPG, PNG or WebP · up to 5 MB", cancel: "Cancel", save: "Save changes", activate: "Save and activate", saving: "Saving…", deactivate: "Deactivate", close: "Close",
  invalidPrice: "Enter a price above zero with no more than two decimal places.", invalidPhoto: "Use a JPG, PNG or WebP photo up to 5 MB.", saveError: "Could not save. Your changes are still here so you can retry.",
};
const it = { setup:"Scheda ingrediente",active:"Attivo in questo negozio",inactive:"Da attivare",price:"Prezzo base dell'ingrediente",priceHelp:"Riferimento per configurare l'ingrediente nelle pizze. Il prezzo finale si definisce nei prodotti e negli extra.",scope:"Prezzo, descrizione e foto vengono salvati solo per la tua attività.",suggestion:"Usa suggerimento: {price}",suggestionHelp:"Media degli altri ingredienti attivi di questa categoria nella tua attività.",aliases:"Alias del catalogo globale",noAliases:"Nessun nome alternativo pubblicato. Puoi cercare il nome principale.",aliasesHelp:"Gli alias sono nomi alternativi dello stesso ingrediente. Si gestiscono e revisionano in Global Manager.",allergens:"Allergeni del catalogo globale",unknown:"Allergeni non indicati",allergenHelp:"Un elenco vuoto non conferma l'assenza di allergeni. Controlla la scheda del fornitore.",knownHelp:"Dati del catalogo globale. Verifica che corrispondano al prodotto del fornitore; le correzioni si gestiscono in Global Manager.",description:"Descrizione per la tua attività",placeholder:"Es. Petto di pollo cotto, tagliato a strisce.",identity:"Identità e traduzioni",reviewed:"Revisionato",pending:"Da revisionare",missing:"Da completare",reviewHelp:"Le traduzioni automatiche appaiono nel backoffice dopo la revisione in Global Manager.",photo:"Carica foto",changePhoto:"Cambia foto",photoHelp:"JPG, PNG o WebP · fino a 5 MB",cancel:"Annulla",save:"Salva modifiche",activate:"Salva e attiva",saving:"Salvataggio…",deactivate:"Disattiva",close:"Chiudi",invalidPrice:"Inserisci un prezzo maggiore di zero, con al massimo due decimali.",invalidPhoto:"Usa una foto JPG, PNG o WebP fino a 5 MB.",saveError:"Salvataggio non riuscito. Le modifiche sono conservate per riprovare." };
const fr = { setup:"Fiche de l’ingrédient",active:"Actif dans ce point de vente",inactive:"À activer",price:"Prix de base de l’ingrédient",priceHelp:"Référence pour configurer cet ingrédient dans les pizzas. Le prix final est défini dans les produits et suppléments.",scope:"Le prix, la description et la photo sont enregistrés uniquement pour votre entreprise.",suggestion:"Utiliser la suggestion : {price}",suggestionHelp:"Moyenne des autres ingrédients actifs de cette catégorie dans votre entreprise.",aliases:"Alias du catalogue global",noAliases:"Aucun autre nom publié. Vous pouvez rechercher le nom principal.",aliasesHelp:"Les alias sont d’autres noms du même ingrédient. Ils sont gérés et vérifiés dans Global Manager.",allergens:"Allergènes du catalogue global",unknown:"Allergènes non renseignés",allergenHelp:"Une liste vide ne confirme pas l’absence d’allergènes. Consultez la fiche du fournisseur.",knownHelp:"Données du catalogue global. Vérifiez leur correspondance avec le produit du fournisseur ; les corrections sont gérées dans Global Manager.",description:"Description pour votre entreprise",placeholder:"Ex. Blanc de poulet cuit, coupé en lamelles.",identity:"Identité et traductions",reviewed:"Vérifié",pending:"À vérifier",missing:"À compléter",reviewHelp:"Les traductions automatiques apparaissent dans le backoffice après vérification dans Global Manager.",photo:"Importer une photo",changePhoto:"Changer la photo",photoHelp:"JPG, PNG ou WebP · jusqu’à 5 Mo",cancel:"Annuler",save:"Enregistrer",activate:"Enregistrer et activer",saving:"Enregistrement…",deactivate:"Désactiver",close:"Fermer",invalidPrice:"Saisissez un prix supérieur à zéro, avec deux décimales au maximum.",invalidPhoto:"Utilisez une photo JPG, PNG ou WebP de 5 Mo maximum.",saveError:"Enregistrement impossible. Vos modifications sont conservées pour réessayer." };
const pt = { setup:"Ficha do ingrediente",active:"Ativo nesta loja",inactive:"Por ativar",price:"Preço base do ingrediente",priceHelp:"Referência para configurar este ingrediente nas pizzas. O preço final é definido nos produtos e extras.",scope:"O preço, a descrição e a foto são guardados apenas para o seu negócio.",suggestion:"Usar sugestão: {price}",suggestionHelp:"Média dos outros ingredientes ativos desta categoria no seu negócio.",aliases:"Nomes alternativos do catálogo global",noAliases:"Não há outros nomes publicados. Pode pesquisar pelo nome principal.",aliasesHelp:"São nomes alternativos do mesmo ingrediente. São geridos e revistos no Global Manager.",allergens:"Alergénios do catálogo global",unknown:"Alergénios não informados",allergenHelp:"Uma lista vazia não confirma a ausência de alergénios. Consulte a ficha do fornecedor.",knownHelp:"Dados do catálogo global. Verifique se correspondem ao produto do fornecedor; as correções são geridas no Global Manager.",description:"Descrição para o seu negócio",placeholder:"Ex. Peito de frango cozido, cortado em tiras.",identity:"Identidade e traduções",reviewed:"Revisto",pending:"Por rever",missing:"Por completar",reviewHelp:"As traduções automáticas aparecem no backoffice após revisão no Global Manager.",photo:"Carregar foto",changePhoto:"Mudar foto",photoHelp:"JPG, PNG ou WebP · até 5 MB",cancel:"Cancelar",save:"Guardar alterações",activate:"Guardar e ativar",saving:"A guardar…",deactivate:"Desativar",close:"Fechar",invalidPrice:"Introduza um preço superior a zero, com até duas casas decimais.",invalidPhoto:"Use uma foto JPG, PNG ou WebP até 5 MB.",saveError:"Não foi possível guardar. As alterações foram mantidas para tentar novamente." };
export const inventoryDetailTranslator = (language) => {
  const dictionary = ({ es, en, it, fr, pt })[String(language).split("-")[0]] || en;
  return (key, params = {}) => (dictionary[key] || en[key] || key).replace(/\{(\w+)\}/g, (match, name) => params[name] ?? match);
};

const allergenNames = {
  SOY: ["Soja", "Soy", "Soia", "Soja", "Soja"], SESAME: ["Sésamo", "Sesame", "Sesamo", "Sésame", "Sésamo"],
  LACTOSE: ["Lactosa", "Lactose", "Lattosio", "Lactose", "Lactose"], SULFITES: ["Sulfitos", "Sulphites", "Solfiti", "Sulfites", "Sulfitos"],
  GLUTEN: ["Gluten", "Gluten", "Glutine", "Gluten", "Glúten"], NUTS: ["Frutos de cáscara", "Nuts", "Frutta a guscio", "Fruits à coque", "Frutos de casca rija"],
  PEANUT: ["Cacahuete", "Peanut", "Arachide", "Arachide", "Amendoim"], GELATIN: ["Gelatina", "Gelatin", "Gelatina", "Gélatine", "Gelatina"],
  CELERY: ["Apio", "Celery", "Sedano", "Céleri", "Aipo"], MUSTARD: ["Mostaza", "Mustard", "Senape", "Moutarde", "Mostarda"],
  FISH: ["Pescado", "Fish", "Pesce", "Poisson", "Peixe"], LUPIN: ["Altramuz", "Lupin", "Lupino", "Lupin", "Tremoço"],
  SHELLFISH: ["Marisco", "Shellfish", "Frutti di mare", "Fruits de mer", "Marisco"], EGG: ["Huevo", "Egg", "Uovo", "Œuf", "Ovo"],
  WHEAT: ["Trigo", "Wheat", "Frumento", "Blé", "Trigo"], COCONUT: ["Coco", "Coconut", "Cocco", "Noix de coco", "Coco"],
};
export const inventoryAllergenLabel = (value, language) => {
  const index = ["es", "en", "it", "fr", "pt"].indexOf(String(language).split("-")[0]);
  return allergenNames[String(value).toUpperCase()]?.[index < 0 ? 1 : index] || value;
};
